### add user

POST http://127.0.0.1:8000/create
Content-Type: application/json

{
  "name": "Ron",
  "age": 35
}


### make friend

POST http://127.0.0.1:8000/make_friends
Content-Type: application/json

{
  "target_id": 2,
  "source_id": 4
}


### delete user

DELETE http://127.0.0.1:8000/user
Content-Type: application/json

{
  "target_id": 2
}


### get all friends of user

GET http://127.0.0.1:8000/friends/2
Content-Type: application/json


### update age of user

PUT http://127.0.0.1:8000/2
Content-Type: application/json

{
  "new_age": 56
}


### get all users

GET http://127.0.0.1:8000/get
Content-Type: application/json