### add user

POST http://127.0.0.1:8000/create
Content-Type: application/json

{
  "name": "Navy",
  "age": 23
}


### make friend

POST http://127.0.0.1:8000/make_friends
Content-Type: application/json

{
  "target_id": "61989b2ed6309b314d4e3248",
  "source_id": "61989b45d6309b314d4e3249"
}


### delete user

DELETE http://127.0.0.1:8000/user
Content-Type: application/json

{
  "target_id": "61989b45d6309b314d4e3249"
}


### get all friends of user

GET http://127.0.0.1:8000/friends/61989b21150965c2cb1aa727
Content-Type: application/json


### update age of user

PUT http://127.0.0.1:8000/4
Content-Type: application/json

{
  "new_age": 56
}


### get all users

GET http://127.0.0.1:8000/get
Content-Type: application/json
